apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --whitelist-domain=.127-0-0-1.sslip.io
        - --redirect-url=https://127-0-0-1.sslip.io/oauth2/callback
        - --skip-provider-button=false
        - --set-xauthrequest=true
        - --pass-user-headers=true
        - --skip-auth-preflight=false
        - --skip-oidc-discovery
        - --cookie-secure=false
        - --cookie-domain=.127-0-0-1.sslip.io
        - --oidc-issuer-url=https://dev-07886404.okta.com
        - --login-url=https://dev-07886404.okta.com/oauth2/v1/authorize
        - --redeem-url=https://dev-07886404.okta.com/oauth2/v1/token
        - --oidc-jwks-url=https://dev-07886404.okta.com/oauth2/v1/keys
        env:
        - name: OAUTH2_PROXY_COOKIE_DOMAINS
          value: ".127-0-0-1.sslip.io"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: ''
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: ''
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ''
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "ca-issuer"    
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    
  name: oauth2-proxy
  namespace: kube-system
spec:
  tls:
  - hosts:
    - "127-0-0-1.sslip.io"
    secretName: oauth2-tls
  rules:
  - host: "127-0-0-1.sslip.io"
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
