# Generated by Django 4.1.2 on 2022-11-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavItems",
            fields=[
                (
                    "userId",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "fitemId",
                    models.JSONField(null=True, verbose_name=models.BigIntegerField()),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("itemId", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.BigIntegerField()),
                ("name", models.CharField(max_length=500)),
                ("condition", models.CharField(max_length=50)),
                ("ph", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=500)),
                ("filename", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=200)),
            ],
        ),
    ]
